### ISSUE TITLE
Issue: Unable to share videos synced from iCloud

### ISSUE THREAD

**Issue by ibrahimdevs** [zoho/salesiq-mobilisten-flutter#2]
Hello,

I followed the setup guideline. Chat works well, I can also send image file from my app but when I select video files, they don't playing and when I try to send video files, they simply not sending, actually nothing happening except closing photo selector screen.

I tried with iOS real device.

**Comment by Rishabh-Raghunath** [comment]
Hello, does this behavior happen for any specific video within the photo library or is the video being selected synced from iCloud?
We weren't able to entirely reproduce the issue in our environment.

**Comment by ibrahimdevs** [comment]
Yes, you're right. I tried it from files folder, it works well. But I try from my photo library, it doesn't work because my photo library all synced iCloud. 

Before I select the same video from Files, it worked well. After my photos library, it doesn't work.
I attached not working situation's video.
https://user-images.githubusercontent.com/2773578/142983993-3f35f49f-c70c-4330-b925-02c123e795d3.MP4

**Comment by Rishabh-Raghunath** [comment]
Thanks for confirming. We'll investigate this issue and roll out an update with the fix.

**Comment by ibrahimdevs** [comment]
@Rishabh-Raghunath Thanks! 
When I was looking for a in-app support solution, I was very happy to see Zoho Sales IQ providing Flutter package too. But this issue stops us to continue with Zoho. I hope you can provide a fix soon.

**Comment by Rishabh-Raghunath** [comment]
Hello @ibrahimdevs, We have rolled out an update which fixes this issue with [Release 1.0.1](https://github.com/zoho/salesiq-mobilisten-flutter/releases/tag/v1.0.1).
Once the package is updated, navigate to the `ios` directory and run the `pod install` command to complete the installation.

This issue is now being marked as closed. Please feel free to reopen the same if you experience an issue with sharing media synced from iCloud.
Thanks for bringing this issue to our notice.
