### ISSUE TITLE
 java.lang.IllegalAccessError: Illegal class access: 'h.e.a.b.h.c' attempting to access 'com.zoho.livechat.android.t' (declaration of 'h.e.a.b.h.c' appears in /data/app/~~CKjGPnvUKkUwwOcMy8CB6A=

### ISSUE THREAD

**Issue by ParthNyatiSwastika** [zoho/salesiq-mobilisten-flutter#20]
App crashing in flutter when trying to open askus section. 

E/AndroidRuntime(17689): java.lang.IllegalAccessError: Illegal class access: 'h.e.a.b.h.c' attempting to access 'com.zoho.livechat.android.t'
(declaration of 'h.e.a.b.h.c' appears in /data/app/~~CKjGPnvUKkUwwOcMy8CB6A=

**Comment by DavidBhahirathan** [comment]
Hi @ParthNyatiSwastika,

Thanks for writing to us. We cannot find the exact cause of the crash due to insufficient crash traces from the logs you've shared. To help us look further into this, please share the crash logs with the file and line numbers so we can narrow down the root cause of the issue. 

Regards,
Bhahirathan M

**Comment by ParthNyatiSwastika** [comment]
After adding following lines in build.grade it start working  - 

    buildTypes {
        release {
            **shrinkResources false**
            **minifyEnabled false**
            // TODO: Add your own signing config for the release build.
            // Signing with the debug keys for now, so `flutter run --release` works.
         }
    }
