### ISSUE TITLE
PlatformException(601, operation failed, null, null)

### ISSUE THREAD

**Issue by ashutosh-mulik** [zoho/salesiq-mobilisten-flutter#22]
Getting PlatformException(601, operation failed, null, null) after following installation steps.

Flutter Doctor 

```
`Flutter 3.3.9 • channel stable • https://github.com/flutter/flutter.git
Framework • revision b8f7f1f986 (10 days ago) • 2022-11-23 06:43:51 +0900
Engine • revision 8f2221fbef
Tools • Dart 2.18.5 • DevTools 2.15.0

Running flutter doctor...
Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.3.9, on Microsoft Windows [Version 10.0.22621.819], locale en-US)
[√] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[√] Chrome - develop for the web
[√] Visual Studio - develop for Windows (Visual Studio Build Tools 2022 17.3.6)
[√] Android Studio (version 2021.3)
[√] VS Code (version 1.73.1)
[√] Connected device (3 available)
[√] HTTP Host Availability

• No issues found!`
```

**Comment by DavidBhahirathan** [comment]
Hi @ashutosh-mulik ,

Thanks for writing to us. Please verify that the package name registered with the SalesIQ for your app is the same as your application's package name. Also, please check whether the app and access key for Android and iOS are correct.

For further queries, please feel free to write us at [support@zohosalesiq.com](mailto:support@zohosalesiq.com). We will be happy to assist you.

Regards,

Bhahirathan M,
Zoho SalesIQ.

**Comment by yasinarik** [comment]
@DavidBhahirathan hello, I got the same error. 

We are using 4 flavors for our application but on the SalesIQ platform, we only have 1 brand slot for our current plan.
the main bundleId is `com.ourcompany.mobile` but this runs only in production. 

I thought that the reason of this initialization issue could be that the access keys are not matching for the flavor bundleIDs.

Can you confirm that?

dev: 'com.ourcompany.mobile.dev'
uat: 'com.ourcompany.mobile.uat'
staging: 'com.ourcompany.mobile.stg'

**Comment by DavidBhahirathan** [comment]
Hi @yasinarik. 

Sorry, It's not possible to use mobilisten with such flavors with the base package name as you have mentioned because the SDK is initialized with the package name that you've registered in the SalesIQ with your application's package with its respective app key and access key. So If the package name is anything other than the registered package name, it won't work.

The only way to use the SDK as per your requirement is to purchase a new add-on brand for your portal. So please use all the keys and package name correctly.
