### ISSUE TITLE
when pod install getting this error 

### ISSUE THREAD

**Issue by vorachirag318** [zoho/salesiq-mobilisten-flutter#36]
I used to this package: salesiq_mobilisten: ^2.1.2
platform :ios, '12.0'
Xcode-14.2

[!] Error installing Mobilisten
[!] /usr/bin/curl -f -L -o /var/folders/zb/mdptnlvj3jv1w2chf02ytyym0000gn/T/d20230424-53645-5dot6x/file.zip https://raw.githubusercontent.com/zoho/SalesIQ-Mobilisten-iOS/v5.0.0/Mobilisten.zip --create-dirs --netrc-optional --retry 2 -A 'CocoaPods/1.12.1 cocoapods-downloader/1.6.3'

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0
curl: (28) Failed to connect to raw.githubusercontent.com port 443 after 75260 ms: Operation timed out
Warning: Problem : timeout. Will retry in 1 seconds. 2 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0
curl: (28) Failed to connect to raw.githubusercontent.com port 443 after 75235 ms: Operation timed out
Warning: Problem : timeout. Will retry in 2 seconds. 1 retries left.
  0     0    0     0    0     0      0      0 --:--:--  0:01:15 --:--:--     0
curl: (28) Failed to connect to raw.githubusercontent.com port 443 after 75323 ms: Operation timed out

**Comment by Venkatesh-iOS** [comment]
Hello @vorachirag318 

After analyzing this issue; we found a failure occurring when connecting with the server "raw.githubusercontent.com." This issue may arise due to network connectivity problems.

To fix this, it is recommended that you check your internet connection before attempting to install the pod.

Best regards,
Venkatesh
Zoho SalesIQ.

**Comment by HAFIZkhan-source** [comment]
I am getting this error too. I have tried 3 different internet providers. But still getting this error

**Comment by Venkatesh-iOS** [comment]
This issue is likely due to an internet connectivity problem with the "raw.githubusercontent.com" server. To resolve it, make sure your device has a stable internet connection.

If the issue persists, please contact us at [support@zohosalesiq.com](mailto:support@zohosalesiq.com) for further debugging assistance. We'll be happy to help.

Regards,
Venkatesh,
Zoho SalesIQ

**Comment by yashas-hm** [comment]
> I am getting this error too. I have tried 3 different internet providers. But still getting this error

Try after sometime. Idk why but that worked for me.
