### ISSUE TITLE
Unhandled Exception: PlatformException(500, mobilisten not initialized, null, null)

### ISSUE THREAD

**Issue by widiastika97** [zoho/salesiq-mobilisten-flutter#51]
I tried to use this plugin on iOS, but an error like this appeared

**Comment by Venkatesh-iOS** [comment]
Hi @widiastika97 

Thank you for reaching out to us. The mentioned issue could be due to incorrect setup with App key, Access key and Bundle ID. Please ensure the accuracy of these keys and try again.

If the issue persists, please get in touch with our support team at [support@zohosalesiq.com](mailto:support@zohosalesiq.com). We'll be more than happy to assist you further. 

Best Regards,
Venkatesh,
Zoho SalesIQ
