### ISSUE TITLE
Zoho chat does not open on Flutter app Android.

### ISSUE THREAD

**Issue by joresv** [zoho/salesiq-mobilisten-flutter#54]
Hi everyone,

I have a problem with the sd zoho on android flutter for a while now in effect the chat button appears correctly but when you click on it nothing happens. I obviously have the latest version of the sdk installed.

`implementation 'com.zoho.salesiq:mobilisten:6.0.2'`

The version of the package I use:
`salesiq_mobilisten: ^4.0.0`

Thank you in advance for any help.

**Comment by bhahirathan-mb-11956** [comment]
Hi @joresv , 
We apologize for any inconvenience caused. This issue seems to be an unusual case. Please write us at support@zoholsalesiq.com with your Mobilisten configuration details (code snippets), portal details, and the app key. We will check it from our side and get back to you. 

Best regards,
Bhahirathan M,
Zoho SalesIQ

**Comment by joresv** [comment]
Hi @bhahirathan-mb-11956  I get this error when I want to leave you an email

![image](https://github.com/zoho/salesiq-mobilisten-flutter/assets/58644982/2c5028e4-4f01-4d4b-9d75-55189fe3e6c8)

**Comment by bhahirathan-mb-11956** [comment]
Hi @joresv

Apologies. Here is the correct email address to reach out to us - "support@zohosalesiq.com". Please mail us the mentioned details and we will get back to you.
